# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('status', models.SmallIntegerField(default=0)),
                ('priority', models.SmallIntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogHasChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(default=1)),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogHasDBOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(default=1)),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogHasRequestOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(default=1)),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChunkHasDBOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(default=1)),
                ('chunk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Chunk')),
            ],
        ),
        migrations.CreateModel(
            name='ChunkHasRequestOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(default=1)),
                ('chunk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Chunk')),
            ],
        ),
        migrations.CreateModel(
            name='DBOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sql', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_template', models.SmallIntegerField(default=0)),
                ('method', models.CharField(max_length=10)),
                ('url', models.URLField(max_length=300)),
                ('header', models.CharField(max_length=500)),
                ('params', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='chunkhasrequestoperation',
            name='request_operation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.RequestOperation'),
        ),
        migrations.AddField(
            model_name='chunkhasdboperation',
            name='db_operation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.DBOperation'),
        ),
        migrations.AddField(
            model_name='cataloghasrequestoperation',
            name='request_operation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.RequestOperation'),
        ),
        migrations.AddField(
            model_name='cataloghasdboperation',
            name='db_operation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.DBOperation'),
        ),
        migrations.AddField(
            model_name='cataloghaschunk',
            name='chunk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Chunk'),
        ),
    ]
