# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20161130_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogHasVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.CharField(choices=[('Project', 'Project'), ('Module', 'Module'), ('Case', 'Case')], max_length=50),
        ),
        migrations.AddField(
            model_name='cataloghasvariables',
            name='catalog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog'),
        ),
        migrations.AddField(
            model_name='cataloghasvariables',
            name='variables_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.RequestOperation'),
        ),
    ]
