# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20161130_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='variable_id',
        ),
        migrations.AddField(
            model_name='variables',
            name='catalog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog'),
        ),
    ]
