# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20161130_0600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variables',
            new_name='Variable',
        ),
    ]
