# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20161130_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloghasdboperation',
            name='catalog_id',
        ),
        migrations.RemoveField(
            model_name='cataloghasdboperation',
            name='db_operation_id',
        ),
        migrations.RemoveField(
            model_name='cataloghasrequestoperation',
            name='catalog_id',
        ),
        migrations.RemoveField(
            model_name='cataloghasrequestoperation',
            name='request_operation_id',
        ),
        migrations.RemoveField(
            model_name='chunkhasdboperation',
            name='chunk_id',
        ),
        migrations.RemoveField(
            model_name='chunkhasdboperation',
            name='db_operation_id',
        ),
        migrations.RemoveField(
            model_name='chunkhasrequestoperation',
            name='chunk_id',
        ),
        migrations.RemoveField(
            model_name='chunkhasrequestoperation',
            name='request_operation_id',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='cataloghaschunk',
            old_name='catalog_id',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='cataloghaschunk',
            old_name='chunk_id',
            new_name='chunk',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='catalog_id',
            new_name='catalog',
        ),
        migrations.AddField(
            model_name='dboperation',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog'),
        ),
        migrations.AddField(
            model_name='dboperation',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Chunk'),
        ),
        migrations.AddField(
            model_name='dboperation',
            name='priority',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requestoperation',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog'),
        ),
        migrations.AddField(
            model_name='requestoperation',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Chunk'),
        ),
        migrations.AddField(
            model_name='requestoperation',
            name='priority',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.CharField(choices=[('Project', 'Project'), ('Module', 'Module'), ('RequestTemplate', 'RequestTemplate'), ('Case', 'Case')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requestoperation',
            name='params',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='CatalogHasDBOperation',
        ),
        migrations.DeleteModel(
            name='CatalogHasRequestOperation',
        ),
        migrations.DeleteModel(
            name='ChunkHasDBOperation',
        ),
        migrations.DeleteModel(
            name='ChunkHasRequestOperation',
        ),
    ]
