# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20161130_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dboperation',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='requestoperation',
            name='catalog',
        ),
    ]
