# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0010_auto_20161130_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='dboperation',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Catalog'),
        ),
    ]
