# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0012_requestoperation_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestoperation',
            name='expect_status',
            field=models.SmallIntegerField(blank=True, default=200, null=True),
        ),
        migrations.AddField(
            model_name='requestoperation',
            name='test_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestoperation',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestoperation',
            name='header',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requestoperation',
            name='method',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='requestoperation',
            name='params',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
