# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0013_auto_20161201_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
