# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0014_chunk_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.DateTimeField(unique=True)),
                ('time_sample', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=50)),
                ('module_name', models.CharField(max_length=50)),
                ('case_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('operation_info', models.TextField()),
                ('operation_result', models.TextField(blank=True, null=True)),
                ('assert_result', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('NIL', 'Nil')], max_length=10)),
                ('assert_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
