# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0016_auto_20161201_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='assert_result',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Error', 'Error'), ('Skip', 'Skip')], max_length=10),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='task_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
