# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0017_auto_20161202_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='task_id',
            field=models.CharField(max_length=50),
        ),
    ]
