# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0018_auto_20161202_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='dboperation',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='requestoperation',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.CharField(choices=[('Project', 'Project'), ('Module', 'Module'), ('RequestTemplate', 'RequestTemplate'), ('Case', 'Case'), ('Chunk', 'Chunk')], max_length=50),
        ),
    ]
