# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0020_auto_20161202_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.CharField(choices=[('Project', 'Project'), ('Module', 'Module'), ('Template', 'Template'), ('Case', 'Case'), ('Chunk', 'Chunk')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='catalog',
            unique_together=set([('name', 'type')]),
        ),
    ]
